/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import controller.AgendaController;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Mucavel
 */
public class AdicionarADM extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarADM
     */
    public AdicionarADM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAdd = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelPass = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonAdicionar = new javax.swing.JButton();
        jLabelFundoAdd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("v3.0 - Adicionar Administrador");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelAdd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelAdd.setText("Adicionar Administrador");
        getContentPane().add(jLabelAdd);
        jLabelAdd.setBounds(60, 10, 220, 24);

        jLabelNome.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(150, 50, 34, 16);

        jTextFieldNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(70, 70, 200, 40);

        jLabelPass.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelPass.setText("Palavra-Passe");
        getContentPane().add(jLabelPass);
        jLabelPass.setBounds(130, 120, 100, 16);

        jPasswordField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField);
        jPasswordField.setBounds(70, 150, 200, 40);

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdicionar);
        jButtonAdicionar.setBounds(120, 200, 100, 40);
        getContentPane().add(jLabelFundoAdd);
        jLabelFundoAdd.setBounds(-4, -3, 340, 270);

        setSize(new java.awt.Dimension(346, 296));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // ADICIONAR ADM
        addAdm();
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jTextFieldNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyPressed
        // ENTER PRESSED
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            addAdm();
        }
    }//GEN-LAST:event_jTextFieldNomeKeyPressed

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyPressed
        // ENTER PRESSED
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            addAdm();
        }
    }//GEN-LAST:event_jPasswordFieldKeyPressed
    private boolean isValid(String name){
        return Pattern.matches("|^[\\pL\\s]+$|u", name);
    }
    private void addAdm(){
        AgendaController agendaC = new AgendaController();
        String nome = jTextFieldNome.getText();
        String password = jPasswordField.getText();
        if(nome == null || nome.isEmpty() || nome.trim().isEmpty() || password == null || password.isEmpty() || password.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos campos!");
        }else if(!isValid(nome)){
            JOptionPane.showMessageDialog(null, "Nome inválidos!");
        }else{
            if(agendaC.addAdmin(nome, password)){
                JOptionPane.showMessageDialog(null, "Administrador Adicionado!");
                dispose();
            }else{
                agendaC.erro_add();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelFundoAdd;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
