/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AgendamentoController;
import java.text.SimpleDateFormat;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.Date;
/**
 *
 * @author Carlos Mucavel
 */
public class Agendamento extends javax.swing.JFrame {
    AgendamentoController agendaControll = new AgendamentoController();
    /**
     * Creates new form Agendamento
     */
    public Agendamento() {
        initComponents();
        hora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAgendamento = new javax.swing.JLabel();
        jLabelFreshlook = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldTel = new javax.swing.JTextField();
        jLabelIdade = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jLabelCorte = new javax.swing.JLabel();
        jComboBoxCorte = new javax.swing.JComboBox<>();
        jLabelPreco = new javax.swing.JLabel();
        jTextFieldPreco = new javax.swing.JTextField();
        jLabelDia = new javax.swing.JLabel();
        jDateChooserDia = new com.toedter.calendar.JDateChooser();
        jLabelHora = new javax.swing.JLabel();
        jComboBoxHora = new javax.swing.JComboBox<>();
        jLabelObserv = new javax.swing.JLabel();
        jScrollPaneTxtArea = new javax.swing.JScrollPane();
        jTextAreaTxtArea = new javax.swing.JTextArea();
        jButtonAgendar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelAgendamentoFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("v2.0 - Agendamento");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelAgendamento.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgendamento.setText("Agendamento");
        getContentPane().add(jLabelAgendamento);
        jLabelAgendamento.setBounds(310, 10, 190, 30);

        jLabelFreshlook.setFont(new java.awt.Font("Monotype Corsiva", 0, 32)); // NOI18N
        jLabelFreshlook.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFreshlook.setText("Fresh Look");
        getContentPane().add(jLabelFreshlook);
        jLabelFreshlook.setBounds(320, 40, 150, 50);

        jLabelNome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(40, 120, 60, 19);

        jTextFieldNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(30, 150, 240, 40);

        jLabelTelefone.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefone.setText("Telefone");
        getContentPane().add(jLabelTelefone);
        jLabelTelefone.setBounds(30, 200, 120, 19);

        jTextFieldTel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldTel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldTel);
        jTextFieldTel.setBounds(30, 230, 240, 40);

        jLabelIdade.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelIdade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdade.setText("Idade");
        getContentPane().add(jLabelIdade);
        jLabelIdade.setBounds(30, 280, 70, 19);

        jTextFieldIdade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldIdade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdadeKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldIdade);
        jTextFieldIdade.setBounds(30, 310, 90, 40);

        jLabelCorte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCorte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorte.setText("Corte");
        getContentPane().add(jLabelCorte);
        jLabelCorte.setBounds(30, 360, 100, 19);

        jComboBoxCorte.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxCorte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Juba", "Carreca", "Punk", "Escovinha Grossa", "Escovinha Fina", "Barba", "Cabelo & Barba" }));
        jComboBoxCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCorteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCorte);
        jComboBoxCorte.setBounds(30, 390, 240, 40);

        jLabelPreco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelPreco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPreco.setText("Preço");
        getContentPane().add(jLabelPreco);
        jLabelPreco.setBounds(30, 440, 50, 19);

        jTextFieldPreco.setEditable(false);
        jTextFieldPreco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldPreco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPreco.setText("50 Meticais");
        jTextFieldPreco.setBorder(null);
        getContentPane().add(jTextFieldPreco);
        jTextFieldPreco.setBounds(30, 470, 240, 40);

        jLabelDia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelDia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDia.setText("Dia");
        getContentPane().add(jLabelDia);
        jLabelDia.setBounds(330, 120, 50, 19);

        jDateChooserDia.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooserDia);
        jDateChooserDia.setBounds(330, 150, 210, 40);
        jDateChooserDia.setMinSelectableDate(new Date());
        jDateChooserDia.setDate(new Date());

        jLabelHora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setText("Hora");
        getContentPane().add(jLabelHora);
        jLabelHora.setBounds(330, 200, 50, 19);

        getContentPane().add(jComboBoxHora);
        jComboBoxHora.setBounds(330, 230, 210, 40);

        jLabelObserv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelObserv.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObserv.setText("Observações");
        getContentPane().add(jLabelObserv);
        jLabelObserv.setBounds(330, 280, 140, 15);

        jTextAreaTxtArea.setColumns(20);
        jTextAreaTxtArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextAreaTxtArea.setLineWrap(true);
        jTextAreaTxtArea.setRows(5);
        jTextAreaTxtArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaTxtAreaKeyTyped(evt);
            }
        });
        jScrollPaneTxtArea.setViewportView(jTextAreaTxtArea);

        getContentPane().add(jScrollPaneTxtArea);
        jScrollPaneTxtArea.setBounds(330, 310, 290, 200);

        jButtonAgendar.setBackground(new java.awt.Color(51, 153, 0));
        jButtonAgendar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAgendar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgendar.setText("Agendar");
        jButtonAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgendar);
        jButtonAgendar.setBounds(630, 310, 130, 40);

        jButtonSair.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSair.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(630, 370, 130, 40);

        jLabelAgendamentoFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/fundoAgenda.jpg"))); // NOI18N
        getContentPane().add(jLabelAgendamentoFundo);
        jLabelAgendamentoFundo.setBounds(-6, -5, 810, 560);

        setSize(new java.awt.Dimension(795, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // SAIR/VOLTAR
        dispose(); 
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jComboBoxCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCorteActionPerformed
        // CORTE
        int index = jComboBoxCorte.getSelectedIndex();
        definirPreco(index);
    }//GEN-LAST:event_jComboBoxCorteActionPerformed
    
    private void jButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarActionPerformed
        // Agendar
        try{
            String nome = jTextFieldNome.getText();
            String tel = jTextFieldTel.getText();
            String telSub = tel.substring(0,2);
            if(tel.length() != 9){
                agendaControll.numeroErro();
            }else{
                int telefone = Integer.parseInt(jTextFieldTel.getText());
                try{
                    int idade = Integer.parseInt(jTextFieldIdade.getText());
                    String corte = String.valueOf(jComboBoxCorte.getSelectedItem());
                    String preco = jTextFieldPreco.getText();
                    SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
                    String dia = date.format(jDateChooserDia.getDate());
                    String hora = String.valueOf(jComboBoxHora.getSelectedItem());
                    String observ = jTextAreaTxtArea.getText();
            
                    if(agendaControll.dados(nome, telefone, idade, corte, preco, dia, hora, observ, telSub)){
                        jTextFieldNome.setText("");
                        jTextFieldTel.setText("");
                        jTextFieldIdade.setText("");
                        jTextAreaTxtArea.setText("");
                    }else{
                        agendaControll.agendaErro();
                    }
                } catch (NumberFormatException r){
                    agendaControll.idadeErro();
                } catch (NullPointerException n){
                    agendaControll.dataErro();
                }
            }
            
        } catch(NumberFormatException | StringIndexOutOfBoundsException e){
            agendaControll.numeroErro();
        }
    }//GEN-LAST:event_jButtonAgendarActionPerformed

    private void jTextFieldTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelKeyTyped
        // Max length TELEFONE
        if (jTextFieldTel.getText().length()>=9) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTelKeyTyped

    private void jTextFieldNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyTyped
        // MAX LENGTH NOME
        if(jTextFieldNome.getText().length() >=30){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNomeKeyTyped

    private void jTextFieldIdadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdadeKeyTyped
        // MAX LENGTH IDADE
        if(jTextFieldIdade.getText().length() >=2){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldIdadeKeyTyped

    private void jTextAreaTxtAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaTxtAreaKeyTyped
        // MAX LENGTH OBSERVACOES
        if(jTextAreaTxtArea.getText().length() >=120){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextAreaTxtAreaKeyTyped
    private void hora(){
        LocalDate local = LocalDate.now();
        DayOfWeek dw = DayOfWeek.from(local);
        int val = dw.getValue();
        System.out.println(dw+" "+val);
        int hm = 8;
        int hmx = 22;
        if(val == 4){
            for(int i = hm; i <hmx; i++){
                jComboBoxHora.addItem(String.valueOf(i)+":00");
                jComboBoxHora.addItem(String.valueOf(i)+":30");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxCorte;
    private javax.swing.JComboBox<String> jComboBoxHora;
    private com.toedter.calendar.JDateChooser jDateChooserDia;
    private javax.swing.JLabel jLabelAgendamento;
    private javax.swing.JLabel jLabelAgendamentoFundo;
    private javax.swing.JLabel jLabelCorte;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelFreshlook;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelObserv;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JScrollPane jScrollPaneTxtArea;
    private javax.swing.JTextArea jTextAreaTxtArea;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldTel;
    // End of variables declaration//GEN-END:variables

    private void definirPreco(int indexValue) {
        int index = indexValue;
        
        switch (index) {
            
        case 0:
            jTextFieldPreco.setText("50 Meticais");
            break;
        case 1:
            jTextFieldPreco.setText("80 Meticais");
            break;
        case 2:
            jTextFieldPreco.setText("150 Meticais");
            break; 
        case 3:
            jTextFieldPreco.setText("120 Meticais");
            break; 
        case 4:
            jTextFieldPreco.setText("100 Meticais");
            break;
        case 5:
            jTextFieldPreco.setText("130 Meticais");
            break;
        case 6:
            jTextFieldPreco.setText("200 Meticais");
            break;
        default:
            break;
    }
        
    }
}
